version: '3.8'
services:
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: farmidea
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: farm_idea
    ports:
      - "3306:3306"
    volumes:
      - "./Back-end/database/data:/var/lib/mysql"
  web-api:
    build: "./Back-end/"
    ports:
      - "8050:8080"
    volumes:
      - "./Back-end/:/app"
    depends_on:
      - db
    links:
      - "db:database"
